import type { GitRunner } from '../git/repository.js';
import { assertControllerBranch, isMissingRef } from '../git/repository.js';
import type { GitHub } from '../github/client.js';
import { ensureDraftPullRequest, findPullRequestByBranch } from '../github/pull-requests.js';
import { applyBootstrap, type BootstrapPlan } from './bootstrap.js';

export interface BootstrapPrResult {
  branch: string;
  pullRequest: number | null;
  filesWritten: string[];
  action: 'created' | 'updated' | 'already_open' | 'no_changes';
  reason?: string;
}

export interface BootstrapPrDeps {
  git: GitRunner;
  github: GitHub;
  slug: string;
  branch: string;
  baseBranch: string;
  branchPrefix: string;
  /** Skip the GitHub side, for local verification. */
  pushAndOpenPr?: boolean;
}

/**
 * Commits the bootstrap output on its own branch and opens a draft PR.
 *
 * Writing straight into the working tree — which is what the earlier version
 * did — leaves nine repositories with untracked files and no record of what
 * changed. The design asks for a reviewable PR precisely because the generated
 * knowledge map is a claim about the repository that a human should check.
 *
 * The whole flow is idempotent: it can be re-run after a crash without
 * producing a second branch or a second PR.
 */
export async function openBootstrapPullRequest(
  plan: BootstrapPlan,
  deps: BootstrapPrDeps,
): Promise<BootstrapPrResult> {
  const { git } = deps;
  assertControllerBranch(deps.branch, deps.branchPrefix, deps.baseBranch);

  const existingPr = deps.pushAndOpenPr === false
    ? null
    : await findPullRequestByBranch(deps.github, deps.slug, deps.branch);

  const startingBranch = await git(plan.repoPath, ['symbolic-ref', '--short', 'HEAD']).catch(() => '');

  // Reuse the branch if it already exists; otherwise branch from the fetched base.
  const branchExists = await git(plan.repoPath, ['show-ref', '--verify', '--quiet', `refs/heads/${deps.branch}`])
    .then(() => true)
    .catch((error: unknown) => {
      if (isMissingRef(error)) return false;
      throw error;
    });

  await git(plan.repoPath, ['fetch', 'origin', deps.baseBranch, '--prune']);
  await git(
    plan.repoPath,
    branchExists
      ? ['checkout', deps.branch]
      : ['checkout', '-b', deps.branch, `origin/${deps.baseBranch}`],
  );

  let filesWritten: string[] = [];
  try {
    filesWritten = applyBootstrap(plan);

    // Stage only what bootstrap produced. A blanket `git add -A` would sweep up
    // whatever the developer happened to have in their tree.
    for (const file of filesWritten) {
      await git(plan.repoPath, ['add', '--', file]);
    }

    const staged = await git(plan.repoPath, ['diff', '--cached', '--name-only']);
    if (!staged.trim()) {
      await restore(git, plan.repoPath, startingBranch);
      return { branch: deps.branch, pullRequest: existingPr?.number ?? null, filesWritten, action: 'no_changes' };
    }

    await git(plan.repoPath, [
      'commit',
      '-m',
      `chore(ai): bootstrap repository knowledge for ${plan.projectId}`,
      '-m',
      commitBody(plan),
    ]);

    if (deps.pushAndOpenPr === false) {
      await restore(git, plan.repoPath, startingBranch);
      return { branch: deps.branch, pullRequest: null, filesWritten, action: 'created', reason: 'local only' };
    }

    await git(plan.repoPath, ['push', '--set-upstream', 'origin', `${deps.branch}:refs/heads/${deps.branch}`]);

    const pr = await ensureDraftPullRequest(deps.github, {
      slug: deps.slug,
      head: deps.branch,
      base: deps.baseBranch,
      title: `chore(ai): bootstrap repository knowledge`,
      body: prBody(plan),
    });

    return {
      branch: deps.branch,
      pullRequest: pr.number,
      filesWritten,
      action: existingPr ? 'already_open' : 'created',
    };
  } finally {
    await restore(git, plan.repoPath, startingBranch);
  }
}

/** Always return the developer to the branch they were on. */
async function restore(git: GitRunner, repoPath: string, branch: string): Promise<void> {
  if (!branch) return;
  await git(repoPath, ['checkout', branch]).catch(() => undefined);
}

function commitBody(plan: BootstrapPlan): string {
  return [
    'Generated by ai-dev-controller.',
    '',
    'Existing documentation was mapped, not moved or deleted.',
    `Preserved ${plan.preserved.length} existing file(s).`,
    plan.derived.commands.length === 0
      ? 'No validation commands could be derived - see unresolved-conflicts.md.'
      : `Derived ${plan.derived.commands.length} validation command(s).`,
  ].join('\n');
}

function prBody(plan: BootstrapPlan): string {
  const commands = plan.derived.commands.length
    ? plan.derived.commands.map((c) => `- \`${c.command}\`${c.required ? ' (required)' : ''}`).join('\n')
    : '**None could be derived.** The controller cannot validate changes here until this is filled in.';

  return [
    '## Repository knowledge bootstrap',
    '',
    'Adds the files the AI dev controller needs to work in this repository.',
    '',
    '**Nothing existing was modified.** Documentation already present was mapped,',
    'not moved or rewritten.',
    '',
    '## Derived validation commands',
    '',
    commands,
    '',
    '## Detected',
    '',
    `- Base branch: \`${plan.baseBranch}\``,
    `- CI trigger: \`${plan.ciTrigger}\``,
    `- Package manager: \`${plan.derived.packageManager}\``,
    `- Existing files preserved: ${plan.preserved.length}`,
    '',
    ...(plan.derived.notes.length
      ? ['## Undetermined', '', ...plan.derived.notes.map((n) => `- ${n}`), '']
      : []),
    '## What to check',
    '',
    'The generated knowledge map is a *claim* about this repository. Please',
    'confirm the categories are right, and that nothing under `historical_notes`',
    'is actually still current.',
    '',
    '---',
    '',
    '_Opened by ai-dev-controller. You are the merge authority._',
  ].join('\n');
}
